<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from resource-management/xml/schema/CRM/ResourceManagement/ResourceConfiguration.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0badba32cdd72d4b78a83eb4eaa11269)
 */
use CRM_ResourceManagement_ExtensionUtil as E;

/**
 * Database access object for the ResourceConfiguration entity.
 */
class CRM_ResourceManagement_DAO_ResourceConfiguration extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_resource_configuration';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ResourceConfiguration ID
   *
   * @var int
   */
  public $id;

  /**
   * Configuration key
   *
   * @var varchar(20)
   */
  public $config_key;

  /**
   * Configuration value
   *
   * @var varchar(256)
   */
  public $config_value;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_resource_configuration';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Resource Configurations') : E::ts('Resource Configuration');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique ResourceConfiguration ID'),
          'required' => TRUE,
          'where' => 'civicrm_resource_configuration.id',
          'table_name' => 'civicrm_resource_configuration',
          'entity' => 'ResourceConfiguration',
          'bao' => 'CRM_ResourceManagement_DAO_ResourceConfiguration',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'config_key' => [
          'name' => 'config_key',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Config Key'),
          'description' => E::ts('Configuration key'),
          'required' => TRUE,
          'where' => 'civicrm_resource_configuration.config_key',
          'table_name' => 'civicrm_resource_configuration',
          'entity' => 'ResourceConfiguration',
          'bao' => 'CRM_ResourceManagement_DAO_ResourceConfiguration',
          'localizable' => 0,
          'add' => NULL,
        ],
        'config_value' => [
          'name' => 'config_value',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Config Value'),
          'description' => E::ts('Configuration value'),
          'where' => 'civicrm_resource_configuration.config_value',
          'table_name' => 'civicrm_resource_configuration',
          'entity' => 'ResourceConfiguration',
          'bao' => 'CRM_ResourceManagement_DAO_ResourceConfiguration',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'resource_configuration', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'resource_configuration', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_config_key' => [
        'name' => 'index_config_key',
        'field' => [
          0 => 'config_key',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_resource_configuration::1::config_key',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
