<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from resource-management/xml/schema/CRM/ResourceManagement/ResourceCalendarColor.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:816fe362a76ff064fc502459ecba9510)
 */
use CRM_ResourceManagement_ExtensionUtil as E;

/**
 * Database access object for the ResourceCalendarColor entity.
 */
class CRM_ResourceManagement_DAO_ResourceCalendarColor extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_resource_calendar_color';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ResourceCalendarColor ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to ResourceCalendar
   *
   * @var int
   */
  public $calendar_id;

  /**
   * Resource participant status ID
   *
   * @var int
   */
  public $status_id;

  /**
   * Hex code for event type display color
   *
   * @var varchar(255)
   */
  public $event_color;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_resource_calendar_color';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Resource Calendar Colors') : E::ts('Resource Calendar Color');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'calendar_id', 'civicrm_resource_calendar', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique ResourceCalendarColor ID'),
          'required' => TRUE,
          'where' => 'civicrm_resource_calendar_color.id',
          'table_name' => 'civicrm_resource_calendar_color',
          'entity' => 'ResourceCalendarColor',
          'bao' => 'CRM_ResourceManagement_DAO_ResourceCalendarColor',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'calendar_id' => [
          'name' => 'calendar_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to ResourceCalendar'),
          'where' => 'civicrm_resource_calendar_color.calendar_id',
          'table_name' => 'civicrm_resource_calendar_color',
          'entity' => 'ResourceCalendarColor',
          'bao' => 'CRM_ResourceManagement_DAO_ResourceCalendarColor',
          'localizable' => 0,
          'FKClassName' => 'CRM_ResourceManagement_DAO_ResourceCalendar',
          'add' => NULL,
        ],
        'status_id' => [
          'name' => 'status_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Resource participant status ID'),
          'where' => 'civicrm_resource_calendar_color.status_id',
          'table_name' => 'civicrm_resource_calendar_color',
          'entity' => 'ResourceCalendarColor',
          'bao' => 'CRM_ResourceManagement_DAO_ResourceCalendarColor',
          'localizable' => 0,
          'add' => NULL,
        ],
        'event_color' => [
          'name' => 'event_color',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Event Color'),
          'description' => E::ts('Hex code for event type display color'),
          'where' => 'civicrm_resource_calendar_color.event_color',
          'table_name' => 'civicrm_resource_calendar_color',
          'entity' => 'ResourceCalendarColor',
          'bao' => 'CRM_ResourceManagement_DAO_ResourceCalendarColor',
          'localizable' => 0,
          'add' => '1.0',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'resource_calendar_color', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'resource_calendar_color', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
