-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_resource_configuration`;
DROP TABLE IF EXISTS `civicrm_resource_calendar_settings`;
DROP TABLE IF EXISTS `civicrm_resource_calendar_participant`;
DROP TABLE IF EXISTS `civicrm_resource_calendar_color`;
DROP TABLE IF EXISTS `civicrm_resource_calendar`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_resource_calendar
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_resource_calendar` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ResourceCalendar ID',
  `calendar_title` varchar(255) COMMENT 'Calendar Title',
  `calendar_type` varchar(64) COMMENT 'Null or resource name',
  `show_end_date` tinyint COMMENT 'Show End Date',
  `show_public_events` tinyint COMMENT 'Show Only Public or All',
  `week_begins_from_day` tinyint COMMENT 'Show week begins on',
  `time_format_24_hour` tinyint COMMENT 'Use 24 hour format',
  `event_template` int unsigned COMMENT 'Null or Resource template id\'s',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_resource_calendar_color
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_resource_calendar_color` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ResourceCalendarColor ID',
  `calendar_id` int unsigned COMMENT 'FK to ResourceCalendar',
  `status_id` int unsigned COMMENT 'Resource participant status ID',
  `event_color` varchar(255) COMMENT 'Hex code for event type display color',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_resource_calendar_color_calendar_id FOREIGN KEY (`calendar_id`) REFERENCES `civicrm_resource_calendar`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_resource_calendar_participant
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_resource_calendar_participant` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ResourceCalendarParticipant ID',
  `resource_calendar_id` int unsigned COMMENT 'FK to Resource Calendar',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `event_color` varchar(255) COMMENT 'Hex code for event type display color',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_resource_calendar_participant_resource_calendar_id FOREIGN KEY (`resource_calendar_id`) REFERENCES `civicrm_resource_calendar`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_resource_calendar_participant_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_resource_calendar_settings
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_resource_calendar_settings` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ResourceCalendarSettings ID',
  `calendar_id` int unsigned COMMENT 'FK to ResourceCalendar',
  `config_key` varchar(20) NOT NULL COMMENT 'Configuration key',
  `config_value` varchar(256) COMMENT 'Configuration value',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_calendar_id_config_key`(calendar_id, config_key),
  CONSTRAINT FK_civicrm_resource_calendar_settings_calendar_id FOREIGN KEY (`calendar_id`) REFERENCES `civicrm_resource_calendar`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_resource_configuration
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_resource_configuration` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ResourceConfiguration ID',
  `config_key` varchar(20) NOT NULL COMMENT 'Configuration key',
  `config_value` varchar(256) COMMENT 'Configuration value',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_config_key`(config_key)
)
ENGINE=InnoDB;
